name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Installing Node Dependencies
        run: |
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile
        continue-on-error: false

      - name: Print cbmp version
        run: npx cbmp --version

      - name: Rendering Bitmaps
        run: yarn render
        continue-on-error: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Installing PyPi Dependencies
        run: python -m pip install --upgrade pip clickgen
        continue-on-error: false

      - name: Print clickgen Version
        run: |
          clickgen --version
          ctgen --version

      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: bin/macOS

      - uses: actions/upload-artifact@v4
        with:
          name: macOS-White
          path: bin/macOS-White
      
      
      - name: Install Hypr dependencies
        run: |
          sudo apt install cmake git build-essential \
            libzip-dev librsvg2-dev libtomlplusplus-dev libcairo2-dev \
            xcur2png
      
      - name: Install hyprlang
        run: |
          git clone https://github.com/hyprwm/hyprlang
          cd hyprlang
          cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
          cmake --build ./build --config Release --target hyprlang -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
          sudo cmake --install ./build
      - name: Install hyprcursor
        run: |
          git clone https://github.com/hyprwm/hyprcursor
          cd hyprcursor
          cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
          cmake --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
          sudo cmake --install build
          
      - name: Generate hyprcursors from xcursors
        run: |
          hyprcursor-util -x themes/macOS
          cp manifest.hl themes/extracted_macOS
          hyprcursor-util -c themes/extracted_macOS
      
      - uses: actions/upload-artifact@v4
        with:
          name: macOS-hyprcursor
          path: bin/theme_macOS

